// This file is generated by the corba.js IDL compiler from 'RTC.idl'.

import { ORB } from 'corba.js'
import * as value from "./RTC_value"

export namespace RTC {

    export interface NameValue extends value.RTC.NameValue {
    }

    export interface PortInterfaceProfile extends value.RTC.PortInterfaceProfile {
    }

    export interface ConnectorProfile extends value.RTC.ConnectorProfile {
    }

    export interface PortProfile extends value.RTC.PortProfile {
    }

    export interface ComponentProfile extends value.RTC.ComponentProfile {
    }

    export interface ExecutionContextProfile extends value.RTC.ExecutionContextProfile {
    }

} // namespace RTC

